### ISSUE TITLE
多GPU训练完成，单GPU推理失败

### ISSUE THREAD

**Issue by DaydreamAtNight** [PhoebusSi/Alpaca-CoT#36]
Python 3.9.12, torch 2.0.0, peft 0.3.0.dev0, transformers 4.28.0.dev0
训练采用多GPU：
```
torchrun --nproc_per_node 8 uniform_finetune.py --model_type llama --model_name_or_path ../llama_weights_converted/7B/ --data alpaca-gpt4-cot --lora_target_modules q_proj v_proj --per_gpu_train_batch_size 32 --gradient_accumulation_steps 2 --learning_rate 3e-4 --epochs 1
```
训练成功，
测试采用单卡，采用测试权重，lora权重加载报错：
LORA_WEIGHTS = "./saved_models/llama_alpaca-gpt4-cot"
```
CUDA_VISIBLE_DEVICES=0 python generate.py --size 7 --model llama
...
Loading checkpoint shards: 100%|█████████████████████████████████████████████| 3/3 [00:14<00:00,  4.84s/it]
Traceback (most recent call last):
  File "/generate.py", line 86, in <module>
    model = PeftModel.from_pretrained(
  File "/home/conda/llama/lib/python3.9/site-packages/peft/peft_model.py", line 164, in from_pretrained
    model = set_peft_model_state_dict(model, adapters_weights)
  File "/home/conda/llama/lib/python3.9/site-packages/peft/utils/save_and_load.py", line 74, in set_peft_model_state_dict
    model.load_state_dict(peft_model_state_dict, strict=False)
  File "/home/conda/llama/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
        size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight: copying a param with shape torch.Size([8, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
        size mismatch for base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight: copying a param with shape torch.Size([4096, 8]) from checkpoint, the shape in current model is torch.Size([4096, 1]).
        size mismatch for base_model.model.model.layers.0.self_attn.v_proj.lora_A.weight: copying a param with shape torch.Size([8, 4096]) from checkpoint, the shape in current model is torch.Size([1, 4096]).
```
看了一下是peft的加载模型出现问题
搜了一下说在torch.load中设置map_device=“cuda:0"就可以，但是报同样的错误
请问有遇到过这种问题么，如何解决

**Comment by zhangyanbo2007** [comment]
同问

**Comment by zhangyanbo2007** [comment]
兄弟，多卡多节点并行可以了吗？》

**Comment by PhoebusSi** [comment]
![image](https://user-images.githubusercontent.com/43233342/229405520-f98b5e9c-b4f9-4203-9423-3b4ed26e39e1.png)
建立了个群，大家来群里交流吧～

**Comment by PhoebusSi** [comment]
请问有尝试过我们最新的generate.py文件吗？

**Comment by DaydreamAtNight** [comment]
> 请问有尝试过我们最新的generate.py文件吗？

有的，但是问题还是一样
