### ISSUE TITLE
huggingface上的数据集无法加载，会报错

### ISSUE THREAD

**Issue by yupeijei1997** [PhoebusSi/Alpaca-CoT#79]
执行以下代码加载数据集
```python
from datasets import load_dataset
datasets = load_dataset("QingyiSi/Alpaca-CoT")
```

报错
```python
Downloading and preparing dataset json/QingyiSi--Alpaca-CoT to /root/.cache/huggingface/datasets/QingyiSi___json/QingyiSi--Alpaca-CoT-a34ced985c873374/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data files: 100%|█████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 2151.29it/s]
Extracting data files: 100%|███████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 269.52it/s]
Generating train split: 141411 examples [00:01, 108035.69 examples/s]Failed to read file '/root/.cache/huggingface/datasets/downloads/33f2a938c99c88922117f8967eecbcaec4ca7d2c257f8de05ca8b99cf2624b35' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Invalid value. in row 0
Traceback (most recent call last):                                   
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 152, in _generate_tables
    dataset = json.load(f)
  File "/data/anaconda3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/data/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/data/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 1860, in _prepare_split_single
    for _, table in generator:
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 155, in _generate_tables
    raise e
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 131, in _generate_tables
    pa_table = paj.read_json(
  File "pyarrow/_json.pyx", line 259, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Invalid value. in row 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/load.py", line 1782, in load_dataset
    builder_instance.download_and_prepare(
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 872, in download_and_prepare
    self._download_and_prepare(
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 967, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 1749, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/data/anaconda3/lib/python3.8/site-packages/datasets/builder.py", line 1892, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
```

**Comment by PhoebusSi** [comment]
我们hf上放的是一个数据集合，需要把需要的数据(json文件)下载下来后，再加载

**Comment by wws0815** [comment]
我把数据加载下来后加载，还是报这样的错误呀

**Comment by wws0815** [comment]
我把数据下载下来加载还是报同样的错误，
from datasets import load_dataset

data_file_path = 'CoT_data.json'
data = load_dataset("json", data_files=data_file_path)
print(data)



错误：

ownloading data files: 100%|██████████| 1/1 [00:00<?, ?it/s]
Extracting data files: 100%|██████████| 1/1 [00:00<00:00, 28.60it/s]
0 tables [00:00, ? tables/s]Failed to read file 'E:\LLM\instruct\Alpaca-CoT-main\data\CoT_data.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Column() changed from object to array in row 0
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\py39\lib\site-packages\datasets\packaged_modules\json\json.py", line 108, in _generate_tables
    pa_table = paj.read_json(
  File "pyarrow\_json.pyx", line 259, in pyarrow._json.read_json
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Column() changed from object to array in row 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LLM\instruct\Alpaca-CoT-main\data\load_data.py", line 9, in <module>
    data = load_dataset("json", data_files=data_file_path)
  File "D:\software\anaconda3\envs\py39\lib\site-packages\datasets\load.py", line 1679, in load_dataset
    builder_instance.download_and_prepare(
  File "D:\software\anaconda3\envs\py39\lib\site-packages\datasets\builder.py", line 704, in download_and_prepare
    self._download_and_prepare(
  File "D:\software\anaconda3\envs\py39\lib\site-packages\datasets\builder.py", line 793, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "D:\software\anaconda3\envs\py39\lib\site-packages\datasets\builder.py", line 1268, in _prepare_split
    for key, table in logging.tqdm(
  File "D:\software\anaconda3\envs\py39\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "D:\software\anaconda3\envs\py39\lib\site-packages\datasets\packaged_modules\json\json.py", line 136, in _generate_tables
    f"This JSON file contain the following fields: {str(list(dataset.keys()))}. "
AttributeError: 'list' object has no attribute 'keys'

Process finished with exit code 1
